main: com.rayzr522.delayme.DelayMe
name: DelayMe
version: 1.0.0
description: Runs a command with a slight delay
author: Rayzr
commands:
  delayme:
    description: DelayMe main command
    usage: "/delayme <player> <command>"
    permission: DelayMe.use
